manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/lunks
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: keymap/lunks
      import: app/west.yml
  self:
    path: config
